[Interface]
Address = 172.16.50.3
PrivateKey = eKbv5uaU0ph6Tg67AMtULcaWBZ66k1I4MvuPYe4MBWg=
ListenPort = 51820
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = CJ9qpns+vuoyfkEM0XEAERgC1XA9XAtOHJj1nv8UfRw=
PresharedKey = P1+8/bJuijzUEHwKRnusAKNqvlt/N+5AgtAVY3yjUII=
Endpoint = 85.55.4.73:51820
AllowedIPs = 172.16.0.0/16
