[Interface]
Address = 172.16.50.3/26
PrivateKey = 2FCz0cbyBuqWAV9XdtNqz84BxwUFC1MN4UQB+fHtakE=
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = OpRXjuw8TBOeKhnBOBaGAmQBlL+dYtS82i86Fxh1cyA=
PresharedKey = omNT+XgJvtisgl7vqLJRCmeH6htMDdST4WTNHkN5TSU=
Endpoint = 192.168.1.40:51820
AllowedIPs = 172.16.0.0/16
PersistentKeepalive = 25
