[Interface]
Address = 10.50.0.3/24
PrivateKey = eKbv5uaU0ph6Tg67AMtULcaWBZ66k1I4MvuPYe4MBWg=
DNS = 172.16.30.10

[Peer]
PublicKey = OpRXjuw8TBOeKhnBOBaGAmQBlL+dYtS82i86Fxh1cyA=
PresharedKey = P1+8/bJuijzUEHwKRnusAKNqvlt/N+5AgtAVY3yjUII=
Endpoint = 85.55.4.73:51820
AllowedIPs = 172.16.0.0/16, 10.50.0.0/24
PersistentKeepalive = 25
