[Interface]
Address = 10.50.0.3/32
PrivateKey = eKNc4vgXl2Z7NuNMIffi0wmBnUfo5cQfP2hWIEpPWlU=
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = QYYFirvJfK8N+Y8OWtO9/D3bikmuRYO3z8lM0IKaXUY=
PresharedKey = ZQB62jMLwqAyGoBQEfXhsZ9msAqi5GDKOJSTf+ItlWw=
Endpoint = 192.168.1.40:51820
AllowedIPs = 172.16.0.0/16, 10.50.0.0/24
PersistentKeepalive = 25
