[Interface]
Address = 10.50.0.4/32
PrivateKey = GHh8ZNfkJFEkcwI0ZH2nUh8Ve4BE335qQ+UgfWJqAmA=
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = QYYFirvJfK8N+Y8OWtO9/D3bikmuRYO3z8lM0IKaXUY=
PresharedKey = b3fX00y8bkVl47KFyUnU/C+ETapwwzAjzSOKlSsBwJ8=
Endpoint = 192.168.1.40:51820
AllowedIPs = 172.16.0.0/16, 10.50.0.0/24
PersistentKeepalive = 25
