[Interface]
Address = 10.50.0.2/32
PrivateKey = uI6inyN0cHhFlTuqiHrqtN02QHoEncp2kdE36vBawE4=
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = QYYFirvJfK8N+Y8OWtO9/D3bikmuRYO3z8lM0IKaXUY=
PresharedKey = UGdoV5EKlFNqE8ueTZLGvzbjUj+/VXbzkooMBAamlPU=
Endpoint = 192.168.1.40:51820
AllowedIPs = 172.16.0.0/16, 10.50.0.0/24
PersistentKeepalive = 25
