[Interface]
Address = 10.50.0.1/24
ListenPort = 51820
PrivateKey = oM01f3RJQ224TBGj6vma8Bu3ovKA5LGi92qSp7uhfW4=

[Peer]
# peer1
PublicKey = mxyfwYrnLtO1XEAHHGLhBhUptJuAKaexzfI8Q86um0o=
PresharedKey = UGdoV5EKlFNqE8ueTZLGvzbjUj+/VXbzkooMBAamlPU=
AllowedIPs = 10.50.0.2/32

[Peer]
# peer2
PublicKey = rvveBFN0olYaSpmuCqm5wzRaWPuDYP+uMBIe+rZbEzw=
PresharedKey = ZQB62jMLwqAyGoBQEfXhsZ9msAqi5GDKOJSTf+ItlWw=
AllowedIPs = 10.50.0.3/32

[Peer]
# peer3
PublicKey = +jOBjdI+hPMJNiB73KwFuH2ZQNf7Q2Pbidxpcgaebh8=
PresharedKey = b3fX00y8bkVl47KFyUnU/C+ETapwwzAjzSOKlSsBwJ8=
AllowedIPs = 10.50.0.4/32
