[Interface]
Address = 172.16.50.4/26
PrivateKey = EBfIXYA/vGKFazU7CoPA1T96uUyibr8BQNmJZF6vMXo=
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = OpRXjuw8TBOeKhnBOBaGAmQBlL+dYtS82i86Fxh1cyA=
PresharedKey = DNBTauC5M6sKORkS3vQyL9BORtPUBQHD8NzyfKx2fUw=
Endpoint = 192.168.1.40:51820
AllowedIPs = 172.16.0.0/16
PersistentKeepalive = 25
