[Interface]
Address = 172.16.50.4
PrivateKey = iIO58Q1/+UBdZW9qe6FNqEUtkfHjb8WmPTQhUY6W4WU=
ListenPort = 51820
DNS = 172.16.30.10,172.16.30.11

[Peer]
PublicKey = CJ9qpns+vuoyfkEM0XEAERgC1XA9XAtOHJj1nv8UfRw=
PresharedKey = 2YjW8eB9p20drps6h0UGJgW5zWMJvvGz0Tsjbq4Cf1Y=
Endpoint = 85.55.4.73:51820
AllowedIPs = 172.16.0.0/16
