[Interface]
Address = 10.50.0.4/24
PrivateKey = iIO58Q1/+UBdZW9qe6FNqEUtkfHjb8WmPTQhUY6W4WU=
DNS = 172.16.30.10

[Peer]
PublicKey = OpRXjuw8TBOeKhnBOBaGAmQBlL+dYtS82i86Fxh1cyA=
PresharedKey = 2YjW8eB9p20drps6h0UGJgW5zWMJvvGz0Tsjbq4Cf1Y=
Endpoint = 85.55.4.73:51820
AllowedIPs = 172.16.0.0/16, 10.50.0.0/24
PersistentKeepalive = 25
