[Interface]
Address = 172.16.50.2/26
PrivateKey = SM0oAgYJR/LdADKrz17UWKQQh36x5zoUj0JufBGpwG4=
DNS = 172.16.30.10

[Peer]
PublicKey = OpRXjuw8TBOeKhnBOBaGAmQBlL+dYtS82i86Fxh1cyA=
PresharedKey = 6o8zybxBl5XVS/u7o+CrIpsY17InNb1oXPXOhLQxia4=
Endpoint = 85.55.4.73:51820
AllowedIPs = 172.16.0.0/16
PersistentKeepalive = 25
